export interface Avaliacao {
    id?: string,
    userId?: string,
    ombro?: string,
    torax?: string,
    abdomem?: string,
    quadril?: string,
    bracoDireito?: string,
    bracoEsquerdo?: string,
    coxaEsquerdo?: string,
    coxaDireita?: string,
    pernaDireita?: string,
    pernaEsquerda?: string,
    peso?: string,
    altura?: string,
    criadoEm?: string, 
    arquivado?: boolean,
}
